config/routes.rb
Rails.application.routes.draw do
  resources :clients do
    collection do
      get 'dashboard', to: 'clients#dashboard'
    end
    resources :deposits
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :deposits
  validates :nome, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Formato de e-mail inválido" }
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :client
  attribute :valor, :decimal, precision: 8, scale: 2

  validates :valor, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.all

    respond_to do |format|
      format.html
      format.json { render json: @clients }
    end
  end

  def show
    @client = Client.find(params[:id])
    @total_deposits = @client.deposits.sum(:valor)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to @client
    else
      render :new
    end
  end

  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Cliente atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @client.deposits.destroy_all
    @client.destroy
    redirect_to clients_url, notice: 'Cliente excluído com sucesso.'
  end  

  def dashboard
    @clients = Client.includes(:deposits).all
    @total_deposits = @clients.sum { |client| client.deposits.sum(:valor) }
  end

    private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:nome, :endereco, :deposito, :email)
  end
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_client

  def index
    @deposits = Deposit.all
  end

  def new
    @deposit = @client.deposits.build
  end

  def show
    @deposit = @client.deposits.find(params[:id])

    respond_to do |format|
      format.html # Para resposta HTML
      format.json { render json: @deposit } # Para resposta JSON
    end
    respond_to(&:html)
  end

  def create
    @deposit = @client.deposits.build(deposit_params)

    if @deposit.save
      redirect_to @client, notice: 'Depósito adicionado com sucesso.'
    else
      flash[:alert] = 'Erro ao salvar o depósito.'
      render :new
    end
  end

  def destroy
    @client = Client.find(params[:client_id])
    @deposit = @client.deposits.find(params[:id])
    @deposit.destroy
    redirect_to client_path(@client), notice: 'Depósito excluído com sucesso.'
  end

  private

  def set_client
    @client = Client.find(params[:client_id])
  end

  def deposit_params
    params.require(:deposit).permit(:valor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/clients/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/chart.js' %>
</head>
<body>
  <h1>Dashboard</h1>

  <%= pie_chart @clients.pluck(:nome, :valor) %>

  <div>
    <h2>Total de Lucro: <%= number_to_currency(@clients.sum { |client| client.deposits.sum(:valor) }, unit: 'R$', precision: 2) %></h2>

    <table border="1">
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Total Depositos</th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.nome %></td>
            <td><%= number_to_currency(client.deposits.sum(:valor), unit: 'R$', precision: 2) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</body>
</html>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= form_with(model: @client, url: client_path(@client), method: :patch) do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit "Atualizar Cliente" %>
  </div>
<% end %>

<style>
body {
  font-family: Arial, sans-serif;
  background-color: #f4f4f4;
}

h1 {
  color: #333;
}

form {
  max-width: 400px;
  margin: 20px auto;
  padding: 20px;
  background-color: #fff;
  border-radius: 5px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

div {
  margin-bottom: 15px;
}

label {
  display: block;
  margin-bottom: 5px;
}

input[type="text"] {
  width: 100%;
  padding: 8px;
  box-sizing: border-box;
  border: 1px solid #ccc;
  border-radius: 4px;
}

input[type="submit"] {
  background-color: #4caf50;
  color: #fff;
  padding: 10px 15px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type="submit"]:hover {
  background-color: #45a049;
}

</style>

app/views/clients/index.html.erb
<style>
  body {
    font-family: Arial, sans-serif;
  }

  h1 {
    color: #007BFF;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    overflow: hidden;
  }

  th, td {
    border: 1px solid #ddd;
    padding: 12px;
    text-align: left;
  }

  th {
    background-color: #007BFF;
    color: white;
  }

  tbody tr:hover {
    background-color: #f5f5f5;
  }

  .button {
    display: inline-block;
    padding: 10px 15px;
    text-decoration: none;
    background-color: #007BFF;
    color: #fff;
    border: 1px solid #007BFF;
    border-radius: 4px;
    cursor: pointer;
  }

  .button:hover {
    background-color: #0056b3;
    border-color: #0056b3;
  }

  .delete-button {
    background-color: #dc3545;
    border-color: #dc3545;
  }

  .delete-button:hover {
    background-color: #c82333;
    border-color: #c82333;
  }
</style>


<h1>Clientes</h1>
<table border="2">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Email</th>
      <th>Orçamento</th>
      <th>Ações</th>
    </tr>
  </thead>

<tbody>
  <% @clients.each do |client| %>
    <tr>
      <td><%= client.nome %></td>
      <td><%= client.endereco %></td>
      <td><%= client.email %></td>
      <td><%= number_to_currency(client.deposits.sum(:valor), unit: 'R$', precision: 2) %></td>
      <td>
        <%= button_to 'Visualizar', client_path(client), method: :get %>
        <%= button_to 'Editar', edit_client_path(client), method: :get %>
        <%= button_to 'Deletar', client_path(client), form: { data: { turbo_confirm: 'Tem certeza?' } }, method: :delete %>
      </td>
    </tr>
  <% end %>

</tbody>

  </tbody>
</table>

app/views/clients/new.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
    }

    form {
      background-color: #fff;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      padding: 20px;
      width: 300px;
      margin-top: 20px;
    }

    div {
      margin-bottom: 15px;
    }

    label {
      display: block;
      font-weight: bold;
      margin-bottom: 5px;
    }

    input {
      width: 100%;
      padding: 8px;
      box-sizing: border-box;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    input[type="submit"] {
      background-color: #4caf50;
      color: #fff;
      cursor: pointer;
    }

    input[type="submit"]:hover {
      background-color: #45a049;
    }
  </style>
</head>
<body>

  <h1 style="text-align: center;">Criar Novo Cliente</h1>

  <%= form_with model: @client do |form| %>
    <form id="client-form">
      <div>
        <%= form.label :nome %>
        <%= form.text_field :nome %>
      </div>

      <div>
        <%= form.label :endereço %>
        <%= form.text_field :endereco %>
      </div>
      
      <div>
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
      
      <div>
        <%= form.submit "Criar Cliente", id: "create-client-btn" %>
      </div>
    </form>
  <% end %>
</body>
</html>

app/views/clients/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }

    .container {
      max-width: 800px;
      margin: 20px auto;
      background-color: #fff;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
      color: #333;
      text-align: center;
    }

    strong {
      font-weight: bold;
    }

    p {
      margin: 10px 0;
    }

    .btn {
      display: inline-block;
      padding: 8px 16px;
      font-size: 14px;
      text-align: center;
      text-decoration: none;
      cursor: pointer;
      border-radius: 4px;
      margin-right: 10px;
    }

    .btn-danger {
      background-color: #d9534f;
      color: #fff;
      border: 1px solid #d9534f;
    }

    .btn-danger:hover {
      background-color: #c9302c;
      border-color: #ac2925;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    th, td {
      border: 1px solid #ddd;
      padding: 12px;
      text-align: left;
    }

    th {
      background-color: #4CAF50;
      color: white;
    }
  </style>
</head>
<body>

<div class="container">
  <h1>Detalhes do Cliente</h1>

  <p><strong>Nome:</strong> <%= @client.nome %></p>
  <p><strong>Endereço:</strong> <%= @client.endereco %></p>
  <p><strong>Email:</strong> <%= @client.email %></p>
  <p><strong>Orçamento:</strong> <%= number_to_currency(@total_deposits, unit: 'R$', precision: 2) %></p>

  <%= link_to 'Ver depósitos', client_deposits_path(@client), class: 'btn' %>
  <%= link_to 'Novo Depósito', new_client_deposit_path(@client), class: 'btn' %>
  <%= link_to 'Voltar', clients_path, class: 'btn btn-danger' %>

  <%= form_with(model: @client, url: client_path(@client), method: :delete, data: { confirm: 'Tem certeza?' }) do |form| %>
  <% end %>

</div>

</body>
</html>

app/views/deposits/index.html.erb
<% if @client.deposits.any? %>
  <h2>Depósitos:</h2>
  <ul>
    <% @client.deposits.each do |deposit| %>
      <li>
        Valor do Depósito: <%= number_to_currency(deposit.valor, unit: 'R$', precision: 2) %>
        <%= link_to 'Excluir', client_deposit_path(@client, deposit), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'delete-link' %>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="no-deposits-container">
  <p class="no-deposits">Nenhum depósito associado a este cliente.</p>
</div>
<% end %>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
ul {
  list-style-type: none;
  padding: 0;
}

li {
  background-color: #fff;
  padding: 10px;
  margin: 10px 0;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
  border-radius: 4px;
}

.no-deposits {
  color: #777;
  text-align: center;
  margin-top: 20px;
}

td a.delete-link:hover {
  text-decoration: underline;
  color: #c0392b;
}

th, td {
  border: 1px solid #ddd;
  padding: 12px;
  text-align: left;
}

th {
  background-color: #4CAF50;
  color: white;
  padding: 12px;
  text-align: left;
}

.delete-link {
  color: #e74c3c;
  text-decoration: none;
  margin-left: 10px;
  cursor: pointer;
}

.delete-link:hover {
  text-decoration: underline;
}

.no-deposits-container {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh; /* Opcional: Isso preencherá a altura da viewport, ajuste conforme necessário */
}

.no-deposits {
  color: #000;
  text-align: center;
  font-style: italic;
  font-size: 50px;
  /* Adicione outros estilos conforme necessário */
}
</style>

app/views/deposits/new.html.erb
<h1>Novo Depósito</h1>

<%= form_with(model: [@client, @deposit], local: true) do |form| %>
  <div class="field">
    <%= form.label :valor %>
    <%= form.number_field :valor, step: '0.01' %>
  </div>

  <div class="actions">
    <%= form.submit 'Adicionar Depósito', class: 'button' %>
  </div>
<% end %>


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
    }

    form {
      width: 300px;
      margin: auto;
      background-color: #fff;
      padding: 20px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
    }

    h1 {
      color: #333;
      text-align: center;
    }

    .field {
      margin-bottom: 20px;
    }

    label {
      display: block;
      font-weight: bold;
      margin-bottom: 5px;
    }

    input[type="text"] {
      width: 100%;
      padding: 8px;
      box-sizing: border-box;
    }

    .actions {
      margin-top: 20px;
    }

    .button {
      background-color: #4CAF50;
      color: white;
      padding: 10px 15px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      cursor: pointer;
      border: none;
      border-radius: 4px;
      width: 100%;
    }

    .button:hover {
      background-color: #45a049;
    }
  </style>
  <title>Novo Depósito</title>
</head>
<body>

app/views/deposits/show.html.erb
<style>
.details-container {
  text-align: center;
  margin-top: 20px;
}

.details-container h1 {
  color: #333;
}

.details-container p {
  color: #555;
  margin-bottom: 20px;
}

.details-container form {
  width: 300px;
  margin: auto;
  background-color: #fff;
  padding: 20px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  border-radius: 8px;
}

.details-container label {
  display: block;
  font-weight: bold;
  margin-bottom: 10px;
}

.details-container input[type="submit"] {
  background-color: #e74c3c;
  color: white;
  padding: 10px 15px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  cursor: pointer;
  border: none;
  border-radius: 4px;
  width: 100%;
}

.details-container input[type="submit"]:hover {
  background-color: #c0392b;
}
</style>
<div class="details-container">
  <h1>Detalhes do Depósito</h1>
  <p>Valor do Depósito: <%= number_to_currency(@deposit.valor, unit: 'R$', precision: 2) %></p>
  <%= form_with(model: @deposit, url: client_deposit_path(@client, @deposit), method: :delete, data: { confirm: 'Tem certeza?' }) do |form| %>
    <%= form.submit 'Excluir' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>General</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="sidenav">
      <%= link_to 'Dashboard', dashboard_clients_path%>
      <%= link_to 'Novo cliente', new_client_path%>
      <%= link_to 'Listar clientes', clients_path%>
    </div>

    <div class="main">
            <%= yield %>
    </div>
  </body>
</html>